brews:
  - ripgrep
  - fd
  - bat
  - eza
  - zoxide
  - fzf
  - git-delta
  - jq
  - yq
  - gh
  - htop
  - tree
  - wget
  - curl
  - unzip
  - gzip
  - tldr
  - direnv
  - yt-dlp
  - vim
  - chezmoi

casks:
  - blender
  - discord
  - jetbrains-toolbox
  - karabiner-elements
  - mactex-no-gui
  - notion
  - raycast
  - tableplus
  - unity-hub
  - visual-studio-code
  - wezterm@nightly
  - zed

vscode_extensions:
  - anthropic.claude-code
  - charliermarsh.ruff
  - docker.docker
  - github.vscode-github-actions
  - github.vscode-pull-request-github
  - hediet.vscode-drawio
  - ms-azuretools.vscode-containers
  - ms-azuretools.vscode-docker
  - ms-python.debugpy
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-python.vscode-python-envs
  - ms-vscode-remote.remote-containers
  - yoavbls.pretty-ts-errors
