min_version = "2026.8.10"

[tools]
bun = "1.4.0"
java = "temurin-25.0.4+7.0.LTS"
node = "24.19.0"
python = "3.14.7"
ruby = "4.0.6"
terraform = "1.15.9"
gcloud = "581.0.0"

[settings]
experimental = true
