min_version = "2026.10.6"

[tools]
bun = "1.4.2"
java = "temurin-25.0.4+101.0.LTS"
node = "24.21.0"
python = "3.15.0"
ruby = "4.0.7"
terraform = "1.16.5"
gcloud = "588.0.0"

[settings]
experimental = true
